sg_localeditor_list:
    pattern:  /editor
    defaults: { _controller: ServerGroveTranslationEditorBundle:Editor:list }

sg_localeditor_update:
    pattern:  /update
    defaults: { _controller: ServerGroveTranslationEditorBundle:Editor:update }

sg_localeditor_add:
    pattern:  /add
    defaults: { _controller: ServerGroveTranslationEditorBundle:Editor:add }

sg_localeditor_remove:
    pattern:  /remove
    defaults: { _controller: ServerGroveTranslationEditorBundle:Editor:remove }
